name: computer_components_shop_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.4
  marquee: ^2.2.3
  dio: ^5.1.1
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/pc_case.svg
    - assets/pc_cpu.svg
    - assets/pc_fan.svg
    - assets/pc_gpu.svg
    - assets/pc_hdd.svg
    - assets/pc_icon.svg
    - assets/pc_mb.svg
    - assets/pc_os.svg
    - assets/pc_psu.svg
    - assets/pc_ram.svg
    - assets/pc_ssd.svg
    - assets/hwr_ico.svg
    - assets/qlt_ico.svg

  fonts:
    - family: Wallpoet
      fonts:
        - asset: assets/Wallpoet-Regular.ttf
